In [1]:
import pandas as pd

data=pd.read_csv('dataset.csv')
data[:5]

    Country  EU  Eurozone  EEA  Schengen   EPI    COL  International  Quality
0   Austria   1         1    1         1  79.6  42.70          69.49    75.64
1   Belgium   1         1    1         1  73.3  40.40          62.33    62.91
2  Bulgaria   1         0    1         0  57.0  68.94          45.11    68.81
3   Croatia   1         0    1         0  63.1  57.22          60.63    61.27
4    Cyprus   1         1    1         0  64.8  51.39          70.62    62.22

In [2]:
w1 = 1
w2 = 2
w3 = 3
w4 = 4

data=pd.read_csv('dataset.csv')

def Weighted(w1,w2,w3,w4):
    #Normalized
    tw = w1+w2+w3+w4
    W1 = w1/tw
    W2 = w2/tw
    W3 = w3/tw
    W4 = w4/tw
    
    Scores = data.EPI*W1+data.COL*W2+data.International*W3+data.Quality*W4
    Subset = list(zip(data.Country,Scores))
    df = pd.DataFrame(data = Subset, columns=['Country', 'Scores'])
    Sorted = df.sort_values(['Scores'], ascending=False)
    Sorted['Rank'] = range(1,32)
    return Sorted

print(Weighted(w1,w2,w3,w4))

        Country  Scores  Rank
18   Luxembourg  74.378     1
14      Ireland  69.939     2
20  Netherlands  68.412     3
30           UK  68.236     4
10      Germany  68.019     5
0       Austria  67.603     6
28       Sweden  67.263     7
26     Slovenia  67.075     8
6       Denmark  65.599     9
21       Norway  65.591    10
13      Iceland  64.327    11
8       Finland  64.111    12
19        Malta  63.656    13
29   Swizerland  63.138    14
4        Cyprus  62.832    15
5         Czech  62.731    16
7       Estonia  61.952    17
23     Portugal  61.868    18
12      Hungary  61.717    19
22       Poland  61.146    20
2      Bulgaria  60.545    21
3       Croatia  60.451    22
9        France  59.741    23
17    Lithuania  59.656    24
11       Greece  59.571    25
27        Spain  59.500    26
1       Belgium  59.273    27
25     Slovakia  59.057    28
16       Latvia  58.963    29
24      Romania  58.908    30
15        Italy  57.001    31